#!/usr/bin/env bash

set -e
set -u
set -o pipefail

app_name=${1:-"node-info"}

app_guid=$(cf app "${app_name}" --guid)
process_guid=$(cf curl "/v3/apps/${app_guid}/processes" | jq '.resources[0].guid' -r)
cf curl "/v3/processes/${process_guid}/stats" | jq '.resources[] | "index \(.index): cell \(.host)"' -r
